FROM ghcr.io/ublue-os/silverblue-nvidia:latest

COPY b-docker.sh /tmp/b-docker.sh
COPY b-tailscale.sh /tmp/b-tailscale.sh
COPY b-firefox.sh /tmp/b-firefox.sh
COPY b-gnome.sh /tmp/b-gnome.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/b-docker.sh && \
    /tmp/b-tailscale.sh && \
    /tmp/b-firefox.sh && \
    /tmp/b-gnome.sh && \
    ostree container commit
