FROM ghcr.io/ublue-os/cosmic-atomic-main:latest

COPY b-add-tailscale.sh /tmp/b-add-tailscale.sh
COPY b-remove-firefox.sh /tmp/b-remove-firefox.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/b-add-tailscale.sh && \
    /tmp/b-remove-firefox.sh && \
    ostree container commit
