FROM quay.io/fedora-ostree-desktops/cosmic-atomic:42

COPY b-docker.sh /tmp/b-docker.sh
COPY b-tailscale.sh /tmp/b-tailscale.sh
COPY b-firefox.sh /tmp/b-firefox.sh
COPY b-cosmic.sh /tmp/b-cosmic.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/b-docker.sh && \
    /tmp/b-tailscale.sh && \
    /tmp/b-firefox.sh && \
    /tmp/b-cosmic.sh && \
    ostree container commit
