FROM quay.io/fedora-ostree-desktops/base-atomic:42

COPY b-docker.sh /tmp/b-docker.sh
COPY b-tailscale.sh /tmp/b-tailscale.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/b-docker.sh && \
    /tmp/b-tailscale.sh && \
    ostree container commit
