FROM ghcr.io/ublue-os/base-main:latest

COPY b-add-docker.sh /tmp/b-add-docker.sh
COPY b-add-tailscale.sh /tmp/b-add-tailscale.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/b-add-docker.sh && \
    /tmp/b-add-tailscale.sh && \
    ostree container commit
