---
name: Main
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-generic.yml
    with:
      imagename: "${{ github.event.repository.name }}"
      imagedesc: "My Linux desktop configuration"
      containerfilepath: "./Containerfile"
    permissions:
      contents: read
      packages: write
      id-token: write